#ifndef _INCLUDE_VERSION_INFORMATION_H_
#define _INCLUDE_VERSION_INFORMATION_H_

/**
 * @file Contains version information.
 * @brief This file will redirect to an autogenerated version if being compiled via
 * the build scripts.
 */

#if defined EXT_GENERATED_BUILD
#include "version_auto.h"
#else

#ifndef EXT_GENERATED_BUILD
#undef BINARY_NAME
#define BINARY_NAME "compctrl.ext.dll\0"
#endif

#define EXT_BUILD_TAG		"manual"
#define EXT_BUILD_REV		"0"
#define EXT_BUILD_CSET		"0"
#define EXT_BUILD_MAJOR		"0"
#define EXT_BUILD_MINOR		"0"
#define EXT_BUILD_RELEASE	"0"

#define EXT_BUILD_UNIQUEID	EXT_BUILD_REV ":" EXT_BUILD_CSET
#define EXT_VERSION_STRING	EXT_BUILD_MAJOR "." EXT_BUILD_MINOR "." EXT_BUILD_RELEASE "-" EXT_BUILD_TAG
#define EXT_VERSION_FILE	0,0,0,0
#endif

#define EXT_BUILD_TIMESTAMP	__DATE__ " " __TIME__

#if !defined(EXT_GENERATED_BUILD)
# define EXT_VERSION 		EXT_VERSION_STRING
# define EXT_BUILD_ID		EXT_BUILD_UNIQUEID
# define EXT_BUILD_TIME 	EXT_BUILD_TIMESTAMP
#endif

#endif /* _INCLUDE_VERSION_INFORMATION_H_ */
